### ISSUE TITLE
Dependecies are not fullfilled on Julia v1.7.2

### ISSUE THREAD

**Issue by StefanPofahl** [JuliaDynamics/SignalDecomposition.jl#13]
Thank for your package, unfortunatly, I cannot install the package on my machine.
Here is the error message:

(@v1.7) pkg> add SignalDecomposition
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package BandedMatrices [aae01518]:
 BandedMatrices [aae01518] log:
 ├─possible versions are: 0.5.1-0.17.0 or uninstalled
 ├─restricted by compatibility requirements with SignalDecomposition [11a47235] to versions: 0.15.0-0.15.25
 │ └─SignalDecomposition [11a47235] log:
 │   ├─possible versions are: 0.1.0-1.0.3 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-1.0.3
 └─restricted by compatibility requirements with FillArrays [1a297f60] to versions: 0.16.12-0.17.0 or uninstalled — no versions left
   └─FillArrays [1a297f60] log:
     ├─possible versions are: 0.2.0-0.13.2 or uninstalled
     └─restricted by compatibility requirements with Parquet2 [98572fba] to versions: 0.13.0-0.13.2
       └─Parquet2 [98572fba] log:
         ├─possible versions are: 0.1.0-0.1.7 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.1.7

**Comment by Datseris** [comment]
I can't reproduce, because I don't have the other packages that make this a problem that you do, e.g., Parquet2. So this isn't a problem with SignalDecomposition really. Anyways, I've increased BandedMatrices dependency. Can you try again with `add SignalDecomposition#master`?

**Comment by StefanPofahl** [comment]
Cool!!! It works fine :-). I will remove the troublemaker "Parquet2".
